// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: grpc/interface.proto

package accessRequest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccessRequestClient is the client API for AccessRequest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccessRequestClient interface {
	AccessRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type accessRequestClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessRequestClient(cc grpc.ClientConnInterface) AccessRequestClient {
	return &accessRequestClient{cc}
}

func (c *accessRequestClient) AccessRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/accessRequest.AccessRequest/accessRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessRequestServer is the server API for AccessRequest service.
// All implementations must embed UnimplementedAccessRequestServer
// for forward compatibility
type AccessRequestServer interface {
	AccessRequest(context.Context, *Request) (*Reply, error)
	mustEmbedUnimplementedAccessRequestServer()
}

// UnimplementedAccessRequestServer must be embedded to have forward compatible implementations.
type UnimplementedAccessRequestServer struct {
}

func (UnimplementedAccessRequestServer) AccessRequest(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccessRequest not implemented")
}
func (UnimplementedAccessRequestServer) mustEmbedUnimplementedAccessRequestServer() {}

// UnsafeAccessRequestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessRequestServer will
// result in compilation errors.
type UnsafeAccessRequestServer interface {
	mustEmbedUnimplementedAccessRequestServer()
}

func RegisterAccessRequestServer(s grpc.ServiceRegistrar, srv AccessRequestServer) {
	s.RegisterService(&AccessRequest_ServiceDesc, srv)
}

func _AccessRequest_AccessRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessRequestServer).AccessRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accessRequest.AccessRequest/accessRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessRequestServer).AccessRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessRequest_ServiceDesc is the grpc.ServiceDesc for AccessRequest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessRequest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accessRequest.AccessRequest",
	HandlerType: (*AccessRequestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "accessRequest",
			Handler:    _AccessRequest_AccessRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/interface.proto",
}
